### PR TITLE
Fix helm chart ingress template

### PR DESCRIPTION
**Pull request by leric7**
**Description**:
Fix helm chart ingress template.

- Correct `.Values.port` for `.Values.ports`
- Correct `.Vales` spelling for `.Values`
- Move `with` for `.Values.ingress.annotations` to enclose only annotations
- Correct `semverCompare` version from `major>.<minor>.<build>` to `major>.<minor>-<build>` format

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by Nana-EC — APPROVED** [review]

**Comment by Nana-EC** [comment]
@leric7 LG however, not all your commits were signed.
Can you sign them and then we can merge this.

Also please note we like to have our PR descriptions capture an overview of the PR changes.
I updated you PR description with a potential sample as reference for future PR submissions. 
Thanks

**Review by isavov — APPROVED** [review]
LGTM

**Comment by leric7** [comment]
It keeps failing to pass signed commit check. Will create a new PR.

**Comment by leric7** [comment]
Created another PR #1318

**Pull request closed without merging**
