### PR TITLE
ContractCallQuery retry logic

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:

In some rare cases `eth_call` is rejected by a precheck with `INSUFFICIENT_TX_FEE`. This PR adds a retry mechanism, that increases the cost with every iteration by a multiplier of `1.1`.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by mshakeg** [comment]
Hi @Ivo-Yankov , just wanted to ask what's the maximum return data size you've got using this approach? And how many retry attempts were required?

**Comment by Ivo-Yankov** [comment]
> Hi @Ivo-Yankov , just wanted to ask what's the maximum return data size you've got using this approach? And how many retry attempts were required?

Hi @mshakeg, I tested it with your contract from #533 with this version of the relay connected to testnet and managed to get a result from `getNotLotsOfData(19150, {gasLimit: 15000000})` with a single retry attempt. And with >19200 I started receiving `INSUFFICIENT_GAS`, so the only limiting factor is the gasLimit.

**Comment by mshakeg** [comment]
@Ivo-Yankov fantastic! 19150*32 = 612800 bytes or 612.8 KB, which will be more than enough for most use cases.

Does it work on the first attempt or does it have to retry? Retrying will obviously entail greater latency which is not ideal.

**Comment by Ivo-Yankov** [comment]
@mshakeg It takes one retry attempt, I haven't tested the increased latency, but the `INSUFFICIENT_TX_FEE` error is thrown as a `precheck` by the consensus node, so it doesn't wait for the full execution time.

**Comment by mshakeg** [comment]
@Ivo-Yankov I see, would it not be better to change the base multiplier from 1.1 to 1.21(i.e. 1.1*1.1) to avoid that retry? even if a single retry only marginally increases latency.

**Comment by Ivo-Yankov** [comment]
The multiplier is only applied if it has failed at least once. I.e. if `currentRetry === 0` then the multiplier will be 1: 
```
const multiplier = Math.pow(baseMultiplier, currentRetry); // 1.1 ^ 0 = 1
```

This is done because most Contract Calls do not require a cost increase. If we apply the 1.1 multiplier every time that would effectively increase the expense of operating the relay by roughly 10%.

**Comment by mshakeg** [comment]
I see, that's fair, I thought it wouldn't be an issue as relay operators receive a refund.

**Review by natanasow — APPROVED** [review]

**Review by georgi-l95 — APPROVED** [review]
LGTM

**Pull request merged**
