### PR TITLE
Optimize `eth_getLogs()`

### PR DESCRIPTION
**Pull request by dimitrovmaksim**
Signed-off-by: Maksim Dimitrov <dimitrov.maksim@gmail.com>

**Description**:
Removes now obsolete queries to the mirror node for each log to fetch block and transaction data

**Related issue(s)**:

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/389

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by dimitrovmaksim** [comment]
I'm not sure if `567` is the correct timeout status code https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/errors/MirrorNodeClientError.ts#L26. Currently I think 2 `eth_getLogs` tests are using this as a timeout code, but it also returns 567 if a mock for a specific request is not found. One of the tests now passes, but actually the error reason is that there's not mock for the request - https://github.com/hashgraph/hedera-json-rpc-relay/blob/536e2038be92914dfd8aa3f1cee7967b4f2797bb/packages/relay/tests/lib/eth.spec.ts#L1339
```
MirrorNodeClientError: Could not find mock for: 
{
  "method": "get",
  "url": "contracts/0x000000000000000000000000000000000000055f/results/logs?timestamp=gte:1651560386.060890949&timestamp=lte:1651560389.060890949"
}
    at MirrorNodeClient.handleError (/Users/maksimdimitrov/Projects/hedera/hedera-json-rpc-relay/packages/relay/src/lib/clients/mirrorNodeClient.ts:21:2947)
    at MirrorNodeClient.<anonymous> (/Users/maksimdimitrov/Projects/hedera/hedera-json-rpc-relay/packages/relay/src/lib/clients/mirrorNodeClient.ts:21:1894)
    at Generator.throw (<anonymous>)
    at rejected (/Users/maksimdimitrov/Projects/hedera/hedera-json-rpc-relay/packages/relay/src/lib/clients/mirrorNodeClient.ts:19:4) {
  statusCode: 567
}
```

The actual mocked requests should be
`mock.onGet(`contracts/${contractAddress1}/results/logs?timestamp=gte:${defaultBlock.timestamp.from}&timestamp=lte:${defaultBlock.timestamp.to}`).reply(567, timeoutError);`

but the tests till passes

**Comment by dimitrovmaksim** [comment]
I think I figured it out. Timeouts will not have  a `response` property so it will always return `unknownServerErrorHttpStatusCode` which is `567`
https://github.com/hashgraph/hedera-json-rpc-relay/blob/536e2038be92914dfd8aa3f1cee7967b4f2797bb/packages/relay/src/lib/clients/mirrorNodeClient.ts#L158

Timeouts will have `error.code == ECONNABORTED`

**Review by Nana-EC — COMMENTED** [review]
LG, just waiting on passing tests

**Review by georgi-l95 — APPROVED** [review]
LGTM!

**Review by Nana-EC — APPROVED** [review]

**Pull request merged**
