### PR TITLE
chore: replaced eth-address with evm-address in code

### LINKED ISSUE #3125: Swap eth address for evm address everywhere in the hbar limiter code
Addressing the following comment https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1804004678
Possibly adress and discuss following comment as well https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1805150333

### PR DESCRIPTION
**Pull request by simzzz**
**Description**:
In this PR, all mentions of EthAddress have been renamed to EvmAddress for better clarity, as suggested in [this comment](https://github.com/hashgraph/hedera-json-rpc-relay/pull/3110#discussion_r1804004678) 

**Related issue(s)**:

Fixes #3125 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by quiet-node** [comment]
@simzzz Heyy thanks for the contribution! Appreciate the time and effort! Could you kindly make a comment on the issue https://github.com/hashgraph/hedera-json-rpc-relay/issues/3125 so I can assign you to the ticket?

**Comment by simzzz** [comment]
My bad, it's signed now and I've added the comment @quiet-node

**Comment by quiet-node** [comment]
> My bad, it's signed now and I've added the comment @quiet-node

Nice thanks!

**Review by quiet-node — APPROVED** [review]
LGTM! Great work and TYVM for the effort! 🚀 🚀 🚀

**Review by Nana-EC — APPROVED** [review]

**Pull request merged**
