### PR TITLE
Handle max pagination

### LINKED ISSUE #1343: Add pagination limit
### Problem

Mirror node pagination calls don't have a pagination limit

### Solution

Add pagination limit

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Nana-EC**
**Description**:
Handle max pagination
- throw on max page
- update tests

**Related issue(s)**:

Fixes #1343 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by georgi-l95 — APPROVED** [review]

**Review by AlfredoG87 — APPROVED** [review]
LGTM

**Review by ebadiere — APPROVED** [review]
LG.

**Review by ebadiere — APPROVED** [review]
LG.

**Review by AlfredoG87 — APPROVED** [review]
👍

**Pull request merged**
