### PR TITLE
Fix README and pnpm inconsistencies

### LINKED ISSUE #1394: Missing `pnpm` dependency
### Description

When I try to run the project following the steps in read me, I always get the following error.

```
> build
> npx lerna run build

lerna notice cli v6.4.1
lerna info versioning independent


    ✖  @hashgraph/json-rpc-relay:build
       > @hashgraph/json-rpc-relay@0.27.0-SNAPSHOT build
       > pnpm run clean && pnpm run compile

       sh: 1: pnpm: not found
       npm ERR! Lifecycle script `build` failed with error:
       npm ERR! Error: command failed
       npm ERR!   in workspace: @hashgraph/json-rpc-relay@0.27.0-SNAPSHOT
       npm ERR!   at location: /home/ubuntu/hedera/hedera-json-rpc-relay/packages/relay
```

This is not a big deal but we should include `pnpm` in the dependency list as we needs it for building the project.

### Steps to reproduce

Clone the project and then run the following steps

```
From the root of the project workspace:

Run npm install. This will create and populate node_modules.
Run npm run setup. This will link the node_modules to the packages, and the packages together.
Run npm run build. This will clean and compile the relay library and the server.
Run npm run start. This will start the server on port 7546.
```

### Additional context

_No response_

### Hedera network

mainnet, testnet, previewnet, other

### Version

lastest 

### Operating system

None

### LINKED ISSUE #1461: Incorrect configuration in README
### Description

Currently, the suggested mirror node configuration in README is wrong. The mirror node URL should not have `/v1/api`. 
image

This makes the relay unable to query data from the mirror node. The correct one should be
```
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com/
```
Not
```
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com/v1/api
```

### Steps to reproduce

Check configuration section in README
https://github.com/hashgraph/hedera-json-rpc-relay#configuration

### Additional context

_No response_

### Hedera network

mainnet, testnet, previewnet

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by Nana-EC**
**Description**:
Fix a few community noted items
- Update README.md to not note `api/v1` suffix to avoid issues in users copying and pasting
- Added pnpm dependency to relay
- Removed pnpm install from dockerFile
- Updated package-lock.json 

**Related issue(s)**:

Fixes #1394 
Fixes #1461 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by AlfredoG87 — APPROVED** [review]
LGTM

**Review by ebadiere — APPROVED** [review]
LG.

**Comment by Nana-EC** [comment]
FYI @pathornteng this addresses 2 of your tickets

**Comment by pathornteng** [comment]
Awesome, thank you @Nana-EC

**Pull request merged**
