### PR TITLE
fix: updated .github/release.yaml to include `internal` and `github_action` labeled PRs

### LINKED ISSUE #3172: Update release.yml to include `internal` and `github_action` labeled PRs
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'Good First Issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22Good+First+Issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue
The `release.yml` in the repository is a tool that automatically generates release notes for `hedera-json-rpc-relay`, currently covering PRs labeled as `enhancement`, `bug`, `documentation`, and `dependencies`. A new category for internal changes should be added to include PRs labeled as `internal` and possibly `github_action`.

### Proposed Solution:
Update `.github/release.yaml` to include internal changes, as shown below:
```diff
changelog:
  exclude:
    labels: ['wontfix', 'question', 'duplicate', 'invalid']
  categories:
    - title: 'Enhancements'
      labels: ['enhancement']
    - title: 'Bug Fixes'
      labels: ['bug']
    - title: 'Documentation'
      labels: ['documentation']
    - title: 'Dependency Upgrades'
      labels: ['dependencies']
+   - title: 'Internal Changes'
+     labels: ['internal', 'github_action']
```

### Example Implementation
Modify `.github/release.yaml` by adding a new category titled "Internal Changes" and associating it with `internal` and `github_action` labels.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by Ritesh-Udgata**
**Description**:
This PR modified the .github/release.yaml to include `internal` and `github_action` labeled PRs

Fixes #3172 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by Ritesh-Udgata** [comment]
Kindly check this and merge before 31

**Comment by quiet-node** [comment]
> Kindly check this and merge before 31

Hey @Ritesh-Udgata, thanks for picking this up and working on it—great job!

A few points (only `1` and `2` require changes from you):

1. It appears the DCO check didn’t pass. Please review the [Sign Off](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md#sign-off) section in the contributing guide to learn more about signing your commit. For this case, you can fix the DCO by running the following commands:
   ```bash
   git rebase HEAD~1 --signoff
   git push -f
   ```
   
2. This commit also needs to be signed with your GPG key. Here’s a helpful resource: [Signing Commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

3. The PR title doesn’t align with the conventional format. There’s a CI check that verifies this, so it’s essential to follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) standard. I’ve updated the title for you this time but it's jsut FYI for your future contributions 😉 

4. Lastly, a more descriptive PR description is preferred. Again, I’ve updated it for you as an FYI for future contributions, so no worries!

**Comment by Ritesh-Udgata** [comment]
Done 👍
 - Added sign off along with gpg key
 - More descriptive PR

**Review by quiet-node — APPROVED** [review]
LGTM

**Comment by Ritesh-Udgata** [comment]
Could You please add hacktoberfest accepted label ? Thanks.

**Review by Nana-EC — APPROVED** [review]

**Comment by quiet-node** [comment]
@Ritesh-Udgata Hi could you kindly rebase and force pushed the branch? We just added an option which skips the `PR Check/Title Checkj` CI job if it's from a forked repo.

**Comment by quiet-node** [comment]
> Could You please add hacktoberfest accepted label ? Thanks.

I've added the labels. Could you tell me if it's missing anything?

**Comment by Ritesh-Udgata** [comment]
Kindly add Hacktober fest accepted label

**Comment by quiet-node** [comment]
> Kindly add Hacktober fest accepted label

@Ritesh-Udgata I have added all these labels
image

Are there any other labels you need me to add?

**Comment by quiet-node** [comment]
Hello @Ritesh-Udgata, the PR Check/Title Check is still failing. Upon reviewing the workflow file, it appears to be the old version of the YAML file. Please rebase with the remote main branch and force push again to bypass the workflow job.

**Comment by quiet-node** [comment]
@Ritesh-Udgata Hmm I still see the [old version of the YAML file](https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/11618744490/workflow). I'm looking at your forked repo, the [release branch](https://github.com/Ritesh-Udgata/hedera-json-rpc-relay/tree/release) indicates that your branch is 13 commits behind the remote `hashgraph:main`. Could you please update your branch and push it again?

**Comment by quiet-node** [comment]
@Ritesh-Udgata I see you forced push again but seems like your [forked repo](https://github.com/Ritesh-Udgata/hedera-json-rpc-relay/tree/release) is still 16 commits behind [remote:main](https://github.com/hashgraph/hedera-json-rpc-relay). 

image

**Comment by quiet-node** [comment]
@Ritesh-Udgata looks like you have updated your forked `main` branch but didn't update your `release`. Please run below to update your `release`:

```bash
git checkout release
git rebase main
git push -f
```

This should update your `release` branch and should fix the problem.

**Comment by quiet-node** [comment]
@Ritesh-Udgata Hmm the PR Check CI still fails. Our team is working on an internal fix and will be available soon. Please be patient! I'll keep you posted!

**Comment by quiet-node** [comment]
Hello @Ritesh-Udgata so our team just pushed in an internal fix for the PR Check / Title Check CI. Could you please update your forked `release` branch again to get the latest changes from remote hashgraph:main?

**Review by rbarkerSL — APPROVED** [review]

**Comment by Ritesh-Udgata** [comment]
Since I contributed, how do i receive the swag ?

**Pull request merged**
