### PR TITLE
Update websocket documentation

### LINKED ISSUE #1190: Add documentation for eth_subscribe
Remove the design doc and add a proper documentation for the WS server.

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:

**Related issue(s)**:

Fixes #1190 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by AlfredoG87 — DISMISSED** [review]
LGTM

**Review by Nana-EC — CHANGES_REQUESTED** [review]
I like.
Please restore the design doc though

**Comment by Nana-EC** [comment]
@Ivo-Yankov should also update the configurations and main README with info or links so devs know how to not only consume but run their won WS-server

**Comment by Ivo-Yankov** [comment]
> @Ivo-Yankov should also update the configurations and main README with info or links so devs know how to not only consume but run their won WS-server

After #1168 is merged running both the relay and websocket server will be done with `docker compose up`, so I don't think we need to update that part of the docs.

**Review by AlfredoG87 — APPROVED** [review]
LG 👍

**Pull request merged**
