### PR TITLE
Add terminationGracePeriodSeconds to chart deployment resource

### LINKED ISSUE #1349: Add terminationGracePeriodSeconds to chart deployment resource
### Problem

`terminationGracePeriodSeconds` is present in charts values but missed getting called in deployment resource

### Solution

Add `terminationGracePeriodSeconds` to chart deployment resource

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Nana-EC**
**Description**:
Add terminationGracePeriodSeconds to chart deployment resource

**Related issue(s)**:

Fixes #1349 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by isavov — APPROVED** [review]
LGTM

**Review by ebadiere — COMMENTED** [review]
How is this tested?

**Comment by Nana-EC** [comment]
> How is this tested?

In the chart CI tests that deploy and run tests mostly.

**Review by AlfredoG87 — APPROVED** [review]
LGTM

**Pull request merged**
